---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hub-agent-dev-portal
  labels:
    {{- include "hub-helm-chart.labels" . | nindent 4 }}
rules:
  - resources:
      - apiportals
      - apis
      - apicollections
      - apiaccesses
      - apigateways
    apiGroups:
      - hub.traefik.io
    verbs:
      - list
      - watch
