---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hub-helm-chart.fullname" . }}-controller
  labels:
    {{- include "hub-helm-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hub-agent-controller
subjects:
  - kind: ServiceAccount
    name: hub-agent-controller
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hub-helm-chart.fullname" . }}-auth-server
  labels:
    {{- include "hub-helm-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hub-agent-auth-server
subjects:
  - kind: ServiceAccount
    name: hub-agent-auth-server
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "hub-helm-chart.fullname" . }}-dev-portal
  labels:
    {{- include "hub-helm-chart.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hub-agent-dev-portal
subjects:
  - kind: ServiceAccount
    name: hub-agent-dev-portal
    namespace: {{ .Release.Namespace }}
