---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-agent-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hub-helm-chart.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-agent-auth-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hub-helm-chart.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-agent-tunnel
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hub-helm-chart.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hub-agent-dev-portal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hub-helm-chart.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.serviceAccount.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
---

