---
apiVersion: v1
kind: Service
metadata:
  name: hub-catch-all
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hub-helm-chart.labels" . | nindent 4 }}
  annotations:
    traefik.ingress.kubernetes.io/service.passhostheader: "false"
spec:
  ports:
    - name: https
      protocol: TCP
      port: 443
  type: ExternalName
  externalName: {{ .Values.catchAllService.externalName }}
