---
apiVersion: v1
kind: Service
metadata:
  name: hub-agent-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hub-helm-chart.labels" . | nindent 4 }}
  {{- with .Values.service.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.controllerDeployment.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      name: hub-agent-webhook
  selector:
    app: hub-agent
    component: controller
---
apiVersion: v1
kind: Service
metadata:
  name: hub-agent-auth-server
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hub-helm-chart.labels" . | nindent 4 }}
  {{- with .Values.service.labels }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
  annotations:
  {{- with .Values.controllerDeployment.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: hub-agent-auth
      protocol: TCP
      targetPort: 8080
  selector:
    app: hub-agent
    component: auth-server
---
apiVersion: v1
kind: Service
metadata:
  name: hub-agent-dev-portal
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "hub-helm-chart.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
  {{- with .Values.devPortalDeployment.annotations }}
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 80
      name: hub-agent-dev-portal
  selector:
    app: hub-agent
    component: dev-portal
